#ifndef CONST_H_INCLUDED
#define CONST_H_INCLUDED

Student *Glossary[26] = {

  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,

};

#endif // CONST_H_INCLUDED
